### ISSUE TITLE
Explain the purpose of this module a bit more

### ISSUE THREAD

**Issue by MickL** [unjs/db0#69]
### Describe the change

I am trying to figure out the prupose of this module. Can you add a few more sentences to the docs to make it more clear?

- Why should I use this module together with Drizzle when I can just use Drizzle? What er the benifits?
- Can I exchange the database drivers depending on the environment? E.g. use Postgres for local dev and Vercel Postgres or Neon for production? If not -> Big feature request from my side :)

Btw. the docs show at the pages [Integrations](https://db0.unjs.io/integrations) and [Connectors](https://db0.unjs.io/connectors) only a very few drivers while in the sidebar there are WAY more :)

### Additional information

- [ ] Would you be willing to help?

**Comment by pi0** [comment]
> Why should I use this module together with Drizzle when I can just use Drizzle? What er the benifits?

1) Preconfigured connectors, mainly make real sense when used in combo with higher level frameworks such as Nitro and Nuxt
2) Seperation of concepts, You have the freedom of using both ORM and direct queries or plug it to another ORM.


> Btw. the docs show at the pages [Integrations](https://db0.unjs.io/integrations) and [Connectors](https://db0.unjs.io/connectors) only a very few drivers while in the sidebar there are WAY more

Only implemented ones are there. More are to come soon.


I'm closing this issue but feel free to make a PR to improve docs i hope it answered your question and please consider using Discussions for questions and discussions instead of issues 🙏🏼

**Comment by pi0** [comment]
Github is fantastic! (button was visible never noticed it needs explicit enable to show for all!) enabled :)

<img width="656" alt="image" src="https://github.com/unjs/db0/assets/5158436/eb0222e9-2513-4d13-85eb-00e2896d05fb">
